spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari.maximum-pool-size: 5
  jpa:
    hibernate.ddl-auto: none     # Flyway se encarga
    open-in-view: false
    show-sql: false
  flyway.enabled: true
server.port: 8080